In [2]:
import numpy as np

# Define a Python list
a = [1, 2, 3]

# Convert it to numpy array
a_vec = np.array(a)

# Check the type of a_vec
print(type(a_vec))

<class 'numpy.ndarray'>


In [139]:
A = [[1, 1, -1], [2, 0, 0], [0, 1, 2]]
A = np.array(A)

# print(A.shape) # Use .shape to print the shape
goal_manual = np.array([[2,1,1],[1,2,1],[1,1,2]])
# print(goal_manual)
goal_v = [2,2,2]
Goal_M = np.ones((4,4),int)
print(Goal_M.ndim)
np.fill_diagonal(Goal_M, goal_v)
A = np.ones((3, 3)) + np.diag([1, 1, 1])
print(Goal_M)
print(A)

2
[[2 1 1 1]
 [1 2 1 1]
 [1 1 2 1]
 [1 1 1 2]]
[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


In [52]:
# Create the vector
arrange_v = np.arange(0, 20, 2)
linspace_v = np.linspace(0, 20, 5)
zeros_m = np.zeros((2,3))
ones_m = np.ones((3, 3))
like_zero_m = np.zeros_like(ones_m)
diag_m = np.diag(linspace_v)
random_m = np.random.randn(3, 3)

# Visualize the vector
print(arrange_v)
print(linspace_v)
print(zeros_m)
print(ones_m)
print(like_zero_m)
print(diag_m)
print(random_m)
print(diag_m.ndim)
print(diag_m.size)
print(diag_m.shape)
print(len(diag_m.shape))
print(diag_m.dtype)

[ 0  2  4  6  8 10 12 14 16 18]
[ 0.  5. 10. 15. 20.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[ 0.  0.  0.  0.  0.]
 [ 0.  5.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.]
 [ 0.  0.  0. 15.  0.]
 [ 0.  0.  0.  0. 20.]]
[[-1.6669777   0.76619868 -0.92851743]
 [ 1.09233702  1.01412024  0.27103801]
 [-2.292629   -1.47704481 -1.34627131]]
2
25
(5, 5)
2
float64


Create an visualize the matrix  and print its shape.

In [68]:
np.arange(4)
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))
a = np.array([1, 2, 3, 10])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

[1 2 3 4 5 6 7 8]


array([ 1,  2,  3, 10,  5,  6,  7,  8])

In [71]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [73]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


#Operations

In [144]:
a = np.array([[1],[-2],[3]])
b = np.array([[1],[5],[-6]])

print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
# print(a**b)
# print(np.log(a))

[[ 2]
 [ 3]
 [-3]]
[[ 0]
 [-7]
 [ 9]]
[[  1]
 [-10]
 [-18]]
[[ 1. ]
 [-0.4]
 [-0.5]]
[[ 0]
 [ 3]
 [-3]]


In [154]:
# import numpy as np

# Dimension of the problem
n = 10

# Create the vectors
x1 = np.linspace(0, 1,n)
# print(f'linspace: {x1}')
x2 = np.random.randn(n)
# print(f'randn: {x2}')

# Create the matrix
A = np.random.randn(n, n)
# print(f'randn A: {A}')

# Compute y1 and y2
y1 = A @ x1
y2 = A @ x2

# Compute y = A(x1 + x2)
y = A @ (x1 + x2)

# Check the equality
print(y)
print(y1 + y2)

[-0.24552483 -0.27403542  0.74408346  2.01274912  0.52714845 -0.38752423
  0.12777977 -0.5561012  -3.12415247 -6.49954355]
[-0.24552483 -0.27403542  0.74408346  2.01274912  0.52714845 -0.38752423
  0.12777977 -0.5561012  -3.12415247 -6.49954355]


In [198]:
# Dimension of the problem
n = 3

# Create the vectors
x1 = np.linspace(0, 1,n)
# print(f'linspace: {x1}')
x2 = np.random.randn(n)

y1 = np.exp(x1)
y2 = np.exp(x2)

y = np.exp(x1+x2)

print(y)
print(y1*y2)

print(np.isclose(y,y1*y2))

[13.91096095  4.62199447  2.62513811]
[13.91096095  4.62199447  2.62513811]
[ True  True  True]


In [208]:
A = np.random.normal(3,3,(10_000_000,))
B = A[A>0]
B[B<0] = 0
print(B)

A = np.random.normal(3, 3, (10_000_000,))

# Create B with same shape as A
B = np.copy(A)  # or B = A.copy()
B[B < 0] = 0

print(B)

[1.26238111 4.81535833 3.09081684 ... 0.74683147 9.38276028 0.96682874]
[ 0.          2.09486044  4.08058464 ...  5.41581079 10.69779219
  3.40834929]


In [207]:
# import numpy as np

# Set the dimension n
n = 4  # you can change this to any size you want

# Create matrix A with normally distributed values
A = np.random.normal(size=(n, n))

# Create matrix B using numpy's where function
# where(condition, value_if_true, value_if_false)
B = np.where(A > 0, A, 0)

print("Matrix A (normally distributed):")
print(A)
print("\nMatrix B (positive values only):")
print(B)

Matrix A (normally distributed):
9.468730769396146

Matrix B (positive values only):
9.468730769396146


In [ ]:
n = 10
A = np.random.randn(n,n) # equal to np.random.normal(0,1,(n,n))

In [234]:
v_norm = np.array([1,0,1])
a_norm = np.array([[1,1,1],
                  [0,-1,1],
                  [0,0,1]])

print(np.linalg.norm(v_norm))
print(np.linalg.norm(a_norm,2))
print(np.linalg.matrix_rank(a_norm))
print(np.linalg.inv(a_norm))
print(np.transpose(a_norm))

a_normp = np.array([[1,1],
                  [0,-1],
                  [0,0]])
print(np.reshape(a_normp,(2,3)))



1.4142135623730951
1.8793852415718169
3
[[ 1.  1. -2.]
 [-0. -1.  1.]
 [ 0.  0.  1.]]
[[ 1  0  0]
 [ 1 -1  0]
 [ 1  1  1]]
[[ 1  1  0]
 [-1  0  0]]


In [237]:
import pandas as pd

# Read data from a csv file
data = pd.read_csv('./US_births_2000-2014_SSA.csv')

# import numpy as np

# Cast into numpy array
np_data = np.array(data)

# Check that the dimension didn't change
print(f"{data.shape} should be equal to {np_data.shape}")

(5479, 5) should be equal to (5479, 5)
